using Geep.ViewModels.CoreVm;
using System;
using System.Collections.Generic;
using System.Text;

namespace Geep.ViewModels.Constants
{
    public static class LgaList
    {
        public static Dictionary<string, List<LocalGovernmentAreaVm>> PopulateLga()
        {
            var lgaList = new Dictionary<string, List<LocalGovernmentAreaVm>>
            {
                {
                    "FEDERAL CAPITAL TERRITORY",
                    new List<LocalGovernmentAreaVm>(){ new LocalGovernmentAreaVm { LgaName = "Gwagwalada", ReferenceId = 278 } ,
                        new LocalGovernmentAreaVm{LgaName="Kuje",ReferenceId=279 },
                        new LocalGovernmentAreaVm{LgaName="Abaji", ReferenceId=276 },
                        new LocalGovernmentAreaVm{LgaName="Municipal Area Council", ReferenceId=281 },
                        new LocalGovernmentAreaVm{LgaName="Bwari", ReferenceId=277 },
                        new LocalGovernmentAreaVm{LgaName="Kwali", ReferenceId=280}}
                },

                {
                    "ABIA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aba North", ReferenceId=1 },
                        new LocalGovernmentAreaVm{LgaName="Aba South",ReferenceId=2 },
                        new LocalGovernmentAreaVm{LgaName="Arochukwu",ReferenceId=3 },
                        new LocalGovernmentAreaVm{LgaName="Bende",ReferenceId=4 },
                        new LocalGovernmentAreaVm{LgaName="Ikwuano",ReferenceId=5},
                        new LocalGovernmentAreaVm{LgaName="Isiala Ngwa North",ReferenceId=6 },
                        new LocalGovernmentAreaVm{LgaName="Isiala Ngwa South",ReferenceId=7 },
                        new LocalGovernmentAreaVm{LgaName="Isuikwuato",ReferenceId=8 },
                        new LocalGovernmentAreaVm{LgaName="Obi Ngwa", ReferenceId=9 },
                        new LocalGovernmentAreaVm{LgaName="Ohafia", ReferenceId=10 },
                        new LocalGovernmentAreaVm{LgaName="Osisioma", ReferenceId=11 },
                        new LocalGovernmentAreaVm{LgaName="Ugwunagbo",ReferenceId=12 },
                        new LocalGovernmentAreaVm{LgaName="Ukwa East",ReferenceId=13 },
                        new LocalGovernmentAreaVm{LgaName="Ukwa West",ReferenceId=14 },
                        new LocalGovernmentAreaVm{LgaName="Umuahia North",ReferenceId=15 },
                        new LocalGovernmentAreaVm{LgaName="Umuahia South",ReferenceId=16 },
                        new LocalGovernmentAreaVm{LgaName="Umu Nneochi",ReferenceId=17} }
                },

                {
                    "ADAMAWA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Demsa",ReferenceId=18 },
                        new LocalGovernmentAreaVm{LgaName="Fufure",ReferenceId=19 },
                        new LocalGovernmentAreaVm{LgaName="Ganye",ReferenceId=20 },
                        new LocalGovernmentAreaVm{LgaName="Gayuk",ReferenceId=21 },
                        new LocalGovernmentAreaVm{LgaName="Girei",ReferenceId=22 },
                        new LocalGovernmentAreaVm{LgaName="Gombi",ReferenceId=23 },
                        new LocalGovernmentAreaVm{LgaName="Hong",ReferenceId=24 },
                        new LocalGovernmentAreaVm{LgaName="Jada",ReferenceId=25 },
                        new LocalGovernmentAreaVm{LgaName="Lamurde",ReferenceId=26 },
                        new LocalGovernmentAreaVm{LgaName="Madagali",ReferenceId=27 },
                        new LocalGovernmentAreaVm{LgaName="Maiha",ReferenceId=28 },
                        new LocalGovernmentAreaVm{LgaName="Mayo Belwa",ReferenceId=29 },
                        new LocalGovernmentAreaVm{LgaName="Michika",ReferenceId=30 },
                        new LocalGovernmentAreaVm{LgaName="Mubi North",ReferenceId=31 },
                        new LocalGovernmentAreaVm{LgaName="Mubi South",ReferenceId=32 },
                        new LocalGovernmentAreaVm{LgaName="Numan",ReferenceId=33 },
                        new LocalGovernmentAreaVm{LgaName="Shelleng",ReferenceId=34 },
                        new LocalGovernmentAreaVm{LgaName="Song",ReferenceId=35 },
                        new LocalGovernmentAreaVm{LgaName="Toungo",ReferenceId=36 },
                        new LocalGovernmentAreaVm{LgaName="Yola North",ReferenceId=37 },
                        new LocalGovernmentAreaVm{LgaName="Yola South",ReferenceId=38 } }
                },
                {
                    "AKWA IBOM",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Abak",ReferenceId=39 },
                        new LocalGovernmentAreaVm{LgaName="Eastern Obolo",ReferenceId=40 },
                        new LocalGovernmentAreaVm{LgaName="Eket",ReferenceId=41 },
                        new LocalGovernmentAreaVm{LgaName="Esit Eket",ReferenceId=42 },
                        new LocalGovernmentAreaVm{LgaName="Essien Udim",ReferenceId=43 },
                        new LocalGovernmentAreaVm{LgaName="Etim Ekpo",ReferenceId=44 },
                        new  LocalGovernmentAreaVm{LgaName="Etinan",ReferenceId=45 },
                        new LocalGovernmentAreaVm{LgaName="Ibeno",ReferenceId=46 },
                        new LocalGovernmentAreaVm{LgaName="Ibesikpo Asutan",ReferenceId=47 },
                        new LocalGovernmentAreaVm{LgaName="Ibiono-Ibom",ReferenceId=48 },
                        new LocalGovernmentAreaVm{LgaName="Ika",ReferenceId=49 },
                        new LocalGovernmentAreaVm{LgaName="Ikono",ReferenceId=50 },
                        new LocalGovernmentAreaVm{LgaName="Ikot Abasi",ReferenceId=51 },
                        new LocalGovernmentAreaVm{LgaName="Ikot Ekpene",ReferenceId=52 },
                        new LocalGovernmentAreaVm{LgaName="Ini",ReferenceId=53 },
                        new LocalGovernmentAreaVm{LgaName="Itu",ReferenceId =54},
                        new LocalGovernmentAreaVm{LgaName="Mbo",ReferenceId=55 },
                        new LocalGovernmentAreaVm{LgaName="Mkpat-Enin",ReferenceId=56 },
                        new LocalGovernmentAreaVm{LgaName="Nsit-Atai",ReferenceId=57 },
                        new LocalGovernmentAreaVm{LgaName="Nsit-Ibom",ReferenceId=58 },
                        new LocalGovernmentAreaVm{LgaName="Nsit-Ubium",ReferenceId=59 },
                        new LocalGovernmentAreaVm{LgaName="Obot Akara",ReferenceId=60 },
                        new LocalGovernmentAreaVm{LgaName="Okobo",ReferenceId=61 },
                        new LocalGovernmentAreaVm{LgaName="Onna",ReferenceId=62 },
                        new LocalGovernmentAreaVm{LgaName="Oron",ReferenceId=63 },
                        new LocalGovernmentAreaVm{LgaName="Oruk Anam",ReferenceId=64 },
                        new LocalGovernmentAreaVm{LgaName="Udung-Uko",ReferenceId=65 },
                        new LocalGovernmentAreaVm{LgaName="Ukanafun",ReferenceId=66 },
                        new LocalGovernmentAreaVm{LgaName="Uruan",ReferenceId=67 },
                        new LocalGovernmentAreaVm{LgaName="Urue-Offong Oruko",ReferenceId=68 },
                        new LocalGovernmentAreaVm{LgaName="Uyo",ReferenceId=69 } }
                },
                {
                    "ANAMBRA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aguata",ReferenceId=70 },
                        new LocalGovernmentAreaVm{LgaName="Anambra East",ReferenceId=71 },
                        new LocalGovernmentAreaVm{LgaName="Anambra West",ReferenceId=72 },
                        new LocalGovernmentAreaVm{LgaName="Anaocha",ReferenceId=73 },
                        new LocalGovernmentAreaVm{LgaName="Awka North",ReferenceId=74 },
                        new LocalGovernmentAreaVm{LgaName="Awka South",ReferenceId=75 },
                        new LocalGovernmentAreaVm{LgaName="Ayamelum",ReferenceId=76 },
                        new LocalGovernmentAreaVm{LgaName="Dunukofia",ReferenceId=77 },
                        new LocalGovernmentAreaVm{LgaName="Ekwusigo",ReferenceId=78 },
                        new LocalGovernmentAreaVm{LgaName="Idemili North",ReferenceId=79 },
                        new LocalGovernmentAreaVm{LgaName="Idemili South",ReferenceId=80 },
                        new LocalGovernmentAreaVm{LgaName="Ihiala",ReferenceId=81 },
                        new LocalGovernmentAreaVm{LgaName="Njikoka",ReferenceId=82 },
                        new LocalGovernmentAreaVm{LgaName="Nnewi North",ReferenceId=83 },
                        new LocalGovernmentAreaVm{LgaName="Nnewi South",ReferenceId=84 },
                        new LocalGovernmentAreaVm{LgaName="Ogbaru",ReferenceId=85 },
                        new LocalGovernmentAreaVm{LgaName="Onitsha North",ReferenceId=86 },
                        new LocalGovernmentAreaVm{LgaName="Onitsha South",ReferenceId=87 },
                        new LocalGovernmentAreaVm{LgaName="Orumba North",ReferenceId=88 },
                        new LocalGovernmentAreaVm{LgaName="Orumba South",ReferenceId=89 },
                        new LocalGovernmentAreaVm{LgaName="Oyi",ReferenceId=90} }
                },
                {
                    "BAUCHI",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Alkaleri",ReferenceId=91 },
                    new LocalGovernmentAreaVm{LgaName="Bauchi",ReferenceId=92 },
                        new LocalGovernmentAreaVm{LgaName="Bogoro",ReferenceId=93 },
                        new LocalGovernmentAreaVm{LgaName="Damban",ReferenceId=94 },
                        new LocalGovernmentAreaVm{LgaName="Darazo",ReferenceId=95 },
                        new LocalGovernmentAreaVm{LgaName="Dass",ReferenceId=96 },
                        new LocalGovernmentAreaVm{LgaName="Gamawa",ReferenceId=97 },
                        new LocalGovernmentAreaVm{LgaName="Ganjuwa",ReferenceId=98 },
                        new LocalGovernmentAreaVm{LgaName="Giade",ReferenceId=99 },
                        new LocalGovernmentAreaVm{LgaName="Itas Gadau",ReferenceId=100 },
                        new LocalGovernmentAreaVm{LgaName="Jama'are",ReferenceId=101 },
                        new LocalGovernmentAreaVm{LgaName="Katagum",ReferenceId=102 },
                        new LocalGovernmentAreaVm{LgaName="Kirfi",ReferenceId=103 },
                        new LocalGovernmentAreaVm{LgaName="Misau",ReferenceId=104 },
                        new LocalGovernmentAreaVm{LgaName="Ningi",ReferenceId=105 },
                        new LocalGovernmentAreaVm{LgaName="Shira",ReferenceId=106 },
                        new LocalGovernmentAreaVm{LgaName="Tafawa Balewa",ReferenceId=107 },
                        new LocalGovernmentAreaVm{LgaName="Toro",ReferenceId=108 },
                        new LocalGovernmentAreaVm{LgaName="Warji",ReferenceId=109 },
                        new LocalGovernmentAreaVm{LgaName="Zaki",ReferenceId=110} }
                },
                {
                    "BAYELSA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Brass",ReferenceId=111 },
                        new LocalGovernmentAreaVm{LgaName="Ekeremor",ReferenceId=112 },
                        new LocalGovernmentAreaVm{LgaName="Kolokuma Opokuma",ReferenceId=113 },
                        new LocalGovernmentAreaVm{LgaName="Nembe",ReferenceId=114 },
                        new LocalGovernmentAreaVm{LgaName="Ogbia",ReferenceId=115 },
                        new LocalGovernmentAreaVm{LgaName="Sagbama",ReferenceId=116 },
                        new LocalGovernmentAreaVm{LgaName="Southern Ijaw",ReferenceId=117 },
                        new LocalGovernmentAreaVm{LgaName="Yenagoa",ReferenceId=118 } }
                },
                {
                    "BENUE",
                    new List<LocalGovernmentAreaVm>() {new LocalGovernmentAreaVm{LgaName="Ado",ReferenceId=119 },
                        new LocalGovernmentAreaVm{LgaName="Agatu",ReferenceId=120 },
                        new LocalGovernmentAreaVm{LgaName="Apa",ReferenceId=121 },
                        new LocalGovernmentAreaVm{LgaName="Buruku",ReferenceId=122 },
                        new LocalGovernmentAreaVm{LgaName="Gboko",ReferenceId=123 },
                        new LocalGovernmentAreaVm{LgaName="Guma",ReferenceId=124 },
                        new LocalGovernmentAreaVm{LgaName="Gwer East",ReferenceId=125 },
                        new LocalGovernmentAreaVm{LgaName="Gwer West",ReferenceId=126 },
                        new LocalGovernmentAreaVm{LgaName="Katsina-Ala",ReferenceId=127 },
                        new LocalGovernmentAreaVm{LgaName="Konshisha",ReferenceId=128 },
                        new LocalGovernmentAreaVm{LgaName="Kwande",ReferenceId=129 },
                        new LocalGovernmentAreaVm{LgaName="Logo",ReferenceId=130 },
                        new LocalGovernmentAreaVm{LgaName="Makurdi",ReferenceId=131 },
                        new LocalGovernmentAreaVm{LgaName="Obi",ReferenceId=132 },
                        new LocalGovernmentAreaVm{LgaName="Ogbadibo",ReferenceId=133 },
                        new LocalGovernmentAreaVm{LgaName="Ohimini",ReferenceId=134 },
                        new LocalGovernmentAreaVm{LgaName="Oju",ReferenceId=135 },
                        new LocalGovernmentAreaVm{LgaName="Okpokwu",ReferenceId=136 },
                        new LocalGovernmentAreaVm{LgaName="Otukpo",ReferenceId=137 },
                        new LocalGovernmentAreaVm{LgaName="Tarka",ReferenceId=138 },
                        new LocalGovernmentAreaVm{LgaName="Ukum",ReferenceId=139 },
                        new LocalGovernmentAreaVm{LgaName="Ushongo",ReferenceId=140 },
                        new LocalGovernmentAreaVm{LgaName="Vandeikya",ReferenceId=141 } }
                },
                {
                    "BORNO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Abadam",ReferenceId=142 },
                        new LocalGovernmentAreaVm{LgaName="Askira/Uba",ReferenceId=143 },
                        new LocalGovernmentAreaVm{LgaName="Bama",ReferenceId=144 },
                        new LocalGovernmentAreaVm{LgaName="Bayo",ReferenceId=145 },
                        new LocalGovernmentAreaVm{LgaName="Biu",ReferenceId=146 },
                        new LocalGovernmentAreaVm{LgaName="Chibok",ReferenceId=147 },
                        new LocalGovernmentAreaVm{LgaName="Damboa",ReferenceId=148 },
                        new LocalGovernmentAreaVm{LgaName="Dikwa",ReferenceId=149 },
                        new LocalGovernmentAreaVm{LgaName="Gubio",ReferenceId=150 },
                        new LocalGovernmentAreaVm{LgaName="Guzamala",ReferenceId=151 },
                        new LocalGovernmentAreaVm{LgaName="Gwoza",ReferenceId=152 },
                        new LocalGovernmentAreaVm{LgaName="Hawul",ReferenceId=153 },
                        new LocalGovernmentAreaVm{LgaName="Jere",ReferenceId=154 },
                        new LocalGovernmentAreaVm{LgaName="Kaga",ReferenceId=155 },
                        new LocalGovernmentAreaVm{LgaName="Kala/Balge",ReferenceId=156 },
                        new LocalGovernmentAreaVm{LgaName="Konduga",ReferenceId=157 },
                        new LocalGovernmentAreaVm{LgaName="Kukawa",ReferenceId=158 },
                        new LocalGovernmentAreaVm{LgaName="Kwaya Kusar",ReferenceId=159 },
                        new LocalGovernmentAreaVm{LgaName="Mafa",ReferenceId=160 },
                        new LocalGovernmentAreaVm{LgaName="Magumeri",ReferenceId=161 },
                        new LocalGovernmentAreaVm{LgaName="Maiduguri",ReferenceId=162 },
                        new LocalGovernmentAreaVm{LgaName="Marte",ReferenceId=163 },
                        new LocalGovernmentAreaVm{LgaName="Mobbar",ReferenceId=164 },
                        new  LocalGovernmentAreaVm{LgaName="Monguno",ReferenceId=165 },
                        new LocalGovernmentAreaVm{LgaName="Ngala",ReferenceId=166 },
                        new LocalGovernmentAreaVm{LgaName="Nganzai",ReferenceId=167 },
                        new LocalGovernmentAreaVm{LgaName="Shani",ReferenceId=168 } }
                },
                {
                    "CROSS RIVER",
                    new List<LocalGovernmentAreaVm>(){ new LocalGovernmentAreaVm{LgaName="Abi",ReferenceId=169 },
                        new LocalGovernmentAreaVm{LgaName="Akamkpa",ReferenceId=170 },
                        new LocalGovernmentAreaVm{LgaName="Akpabuyo",ReferenceId=171 },
                        new LocalGovernmentAreaVm{LgaName="Bakassi",ReferenceId=172 },
                        new LocalGovernmentAreaVm{LgaName="Bekwarra",ReferenceId=173 },
                        new LocalGovernmentAreaVm{LgaName="Biase",ReferenceId=174 },
                        new LocalGovernmentAreaVm{LgaName="Boki",ReferenceId=175 },
                        new LocalGovernmentAreaVm{LgaName="Calabar Municipal",ReferenceId=176 },
                        new LocalGovernmentAreaVm{LgaName="Calabar South",ReferenceId=177 },
                        new LocalGovernmentAreaVm{LgaName="Etung",ReferenceId=178 },
                        new LocalGovernmentAreaVm{LgaName="Ikom",ReferenceId=179 },
                        new LocalGovernmentAreaVm{LgaName="Obanliku",ReferenceId=180 },
                        new LocalGovernmentAreaVm{LgaName="Obubra",ReferenceId=181 },
                        new LocalGovernmentAreaVm{LgaName="Obudu",ReferenceId=182},
                        new LocalGovernmentAreaVm{LgaName="Odukpani",ReferenceId=183 },
                        new LocalGovernmentAreaVm{LgaName="Ogoja",ReferenceId=184 },
                        new LocalGovernmentAreaVm{LgaName="Yakuur",ReferenceId=185 },
                        new LocalGovernmentAreaVm{LgaName="Yala",ReferenceId=186 } }
                },
                {
                    "DELTA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aniocha North",ReferenceId=187 },
                        new LocalGovernmentAreaVm{LgaName="Aniocha South",ReferenceId=188 },
                        new LocalGovernmentAreaVm{LgaName="Bomadi",ReferenceId=189 },
                        new LocalGovernmentAreaVm{LgaName="Burutu",ReferenceId=190 },
                        new LocalGovernmentAreaVm{LgaName="Ethiope East",ReferenceId=191 },
                        new LocalGovernmentAreaVm{LgaName="Ethiope West",ReferenceId=192 },
                        new LocalGovernmentAreaVm{LgaName="Ika North East",ReferenceId=193 },
                        new LocalGovernmentAreaVm{LgaName="Ika South",ReferenceId=194 },
                        new LocalGovernmentAreaVm{LgaName="Isoko North",ReferenceId=195 },
                        new LocalGovernmentAreaVm{LgaName="Isoko South",ReferenceId=196 },
                        new LocalGovernmentAreaVm{LgaName="Ndokwa East",ReferenceId=197 },
                        new LocalGovernmentAreaVm{LgaName="Ndokwa West",ReferenceId=198 },
                        new LocalGovernmentAreaVm{LgaName="Okpe",ReferenceId=199},
                        new LocalGovernmentAreaVm{LgaName="Oshimili North",ReferenceId=200 },
                        new LocalGovernmentAreaVm{LgaName="Oshimili South",ReferenceId=201 },
                        new LocalGovernmentAreaVm{LgaName="Patani",ReferenceId=202 },
                        new LocalGovernmentAreaVm{LgaName="Sapele",ReferenceId=203 },
                        new LocalGovernmentAreaVm{LgaName="Udu",ReferenceId=204 },
                        new LocalGovernmentAreaVm{LgaName="Ughelli North",ReferenceId=205 },
                        new LocalGovernmentAreaVm{LgaName="Ughelli South",ReferenceId=206 },
                        new LocalGovernmentAreaVm{LgaName="Ukwuani",ReferenceId=207 },
                        new LocalGovernmentAreaVm{LgaName="Uvwie",ReferenceId=208 },
                        new LocalGovernmentAreaVm{LgaName="Warri North",ReferenceId=209 },
                        new LocalGovernmentAreaVm{LgaName="Warri South",ReferenceId=210 },
                        new LocalGovernmentAreaVm{LgaName="Warri South West",ReferenceId=211 } }
                },
                {
                    "EBONYI",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Abakaliki",ReferenceId=212 },
                        new LocalGovernmentAreaVm{LgaName="Afikpo North",ReferenceId=213 },
                        new LocalGovernmentAreaVm{LgaName="Afikpo South(Edda)",ReferenceId=214 },
                        new LocalGovernmentAreaVm{LgaName="Ebonyi",ReferenceId=215 },
                        new LocalGovernmentAreaVm{LgaName="Ezza North",ReferenceId=216 },
                        new LocalGovernmentAreaVm{LgaName="Ezza South",ReferenceId=217 },
                        new LocalGovernmentAreaVm{LgaName="Ikwo",ReferenceId=218 },
                        new LocalGovernmentAreaVm{LgaName="Ishielu",ReferenceId=219 },
                        new LocalGovernmentAreaVm{LgaName="Ivo",ReferenceId=220 },
                        new LocalGovernmentAreaVm{LgaName="Izzi",ReferenceId=221 },
                        new LocalGovernmentAreaVm{LgaName="Ohaozara",ReferenceId=222 },
                        new LocalGovernmentAreaVm{LgaName="Ohaukwu",ReferenceId=223 },
                        new LocalGovernmentAreaVm{LgaName="Onicha",ReferenceId=224 } }
                },
                {
                    "EDO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Akoko-Edo",ReferenceId=225 },
                        new LocalGovernmentAreaVm{LgaName="Egor",ReferenceId=226 },
                        new LocalGovernmentAreaVm{LgaName="Esan Central",ReferenceId=227 },
                        new LocalGovernmentAreaVm{LgaName="Esan North-East",ReferenceId=228 },
                        new LocalGovernmentAreaVm{LgaName="Esan South-East",ReferenceId=229 },
                        new LocalGovernmentAreaVm{LgaName="Esan West",ReferenceId=230 },
                        new LocalGovernmentAreaVm{LgaName="Etsako Central",ReferenceId=231 },
                        new LocalGovernmentAreaVm{LgaName="Etsako East",ReferenceId=232 },
                        new LocalGovernmentAreaVm{LgaName="Etsako West",ReferenceId=233 },
                        new LocalGovernmentAreaVm{LgaName="Igueben",ReferenceId=234 },
                        new LocalGovernmentAreaVm{LgaName="Ikpoba Okha",ReferenceId=235 },
                        new LocalGovernmentAreaVm{LgaName="Orhionmwon",ReferenceId=236 },
                        new LocalGovernmentAreaVm{LgaName="Oredo",ReferenceId=237 },
                        new LocalGovernmentAreaVm{LgaName="Ovia North-East",ReferenceId=238 },
                        new LocalGovernmentAreaVm{LgaName="Ovia South-West",ReferenceId=239 },
                        new LocalGovernmentAreaVm{LgaName="Owan East",ReferenceId=240 },
                        new LocalGovernmentAreaVm{LgaName="Owan West",ReferenceId=241 },
                        new LocalGovernmentAreaVm{LgaName="Uhunmwonde",ReferenceId=242 } }
                },
                {
                    "EKITI",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Ado Ekiti",ReferenceId=243 },
                        new LocalGovernmentAreaVm{LgaName="Efon",ReferenceId=244 },
                        new LocalGovernmentAreaVm{LgaName="Ekiti East",ReferenceId=245 },
                        new LocalGovernmentAreaVm{LgaName="Ekiti South-West",ReferenceId=246 },
                        new LocalGovernmentAreaVm{LgaName="Ekiti West",ReferenceId=247 },
                        new LocalGovernmentAreaVm{LgaName="Emure",ReferenceId=248 },
                        new LocalGovernmentAreaVm{LgaName="Gbonyin",ReferenceId=249 },
                        new LocalGovernmentAreaVm{LgaName="Ido/Osi",ReferenceId=250 },
                        new LocalGovernmentAreaVm{LgaName="Ijero",ReferenceId=251 },
                        new LocalGovernmentAreaVm{LgaName="Ikere",ReferenceId=252 },
                        new LocalGovernmentAreaVm{LgaName="Ikole",ReferenceId=253 },
                        new LocalGovernmentAreaVm{LgaName="Ilejemeje",ReferenceId=254 },
                        new LocalGovernmentAreaVm{LgaName="Irepodun/Ifelodun",ReferenceId=255 },
                        new LocalGovernmentAreaVm{LgaName="Ise Orun",ReferenceId=256 },
                        new LocalGovernmentAreaVm{LgaName="Moba",ReferenceId=257 },
                        new LocalGovernmentAreaVm{LgaName="Oye",ReferenceId=258 } }
                },
                {
                    "ENUGU",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aninrin",ReferenceId=259 },
                        new LocalGovernmentAreaVm{LgaName="Awgu",ReferenceId=260 },
                        new LocalGovernmentAreaVm{LgaName="Enugu East",ReferenceId=261 },
                        new LocalGovernmentAreaVm{LgaName="Enugu North",ReferenceId=262 },
                        new LocalGovernmentAreaVm{LgaName="Enugu South",ReferenceId=263 },
                        new LocalGovernmentAreaVm{LgaName="Ezeagu",ReferenceId=264 },
                        new LocalGovernmentAreaVm{LgaName="Igbo Etiti",ReferenceId=265 },
                        new LocalGovernmentAreaVm{LgaName="Igbo Eze North",ReferenceId=266 },
                        new LocalGovernmentAreaVm{LgaName="Igbo Eze South",ReferenceId=267 },
                        new LocalGovernmentAreaVm{LgaName="Isi Uzo",ReferenceId=268 },
                        new LocalGovernmentAreaVm{LgaName="Nkanu East",ReferenceId=269 },
                        new LocalGovernmentAreaVm{LgaName="Nkanu West",ReferenceId=270 },
                        new LocalGovernmentAreaVm{LgaName="Nsukka",ReferenceId=271 },
                        new LocalGovernmentAreaVm{LgaName="Oji River",ReferenceId=272 },
                        new LocalGovernmentAreaVm{LgaName="Udenu",ReferenceId=273 },
                        new LocalGovernmentAreaVm{LgaName="Udi",ReferenceId=274 },
                        new LocalGovernmentAreaVm{LgaName="Uzo Uwani",ReferenceId=275 } }
                },
                {
                    "GOMBE",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Akko",ReferenceId=282 },
                        new LocalGovernmentAreaVm{LgaName="Balanga",ReferenceId=283 },
                        new LocalGovernmentAreaVm{LgaName="Billiri",ReferenceId=284 },
                        new LocalGovernmentAreaVm{LgaName="Dukku",ReferenceId=285 },
                        new LocalGovernmentAreaVm{LgaName="Funakaye",ReferenceId=286 },
                        new LocalGovernmentAreaVm{LgaName="Gombe",ReferenceId=287 },
                        new LocalGovernmentAreaVm{LgaName="Kaltungo",ReferenceId=288 },
                        new LocalGovernmentAreaVm{LgaName="Kwami",ReferenceId=289 },
                        new LocalGovernmentAreaVm{LgaName="Nafada",ReferenceId=290 },
                        new LocalGovernmentAreaVm{LgaName="Shongom",ReferenceId=291 },
                        new LocalGovernmentAreaVm{LgaName="Yamaltu/Deba",ReferenceId=292 } }
                },
                {
                    "IMO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aboh-Mbaise",ReferenceId=293 },
                        new LocalGovernmentAreaVm{LgaName="Ahiazu Mbaise",ReferenceId=294 },
                        new LocalGovernmentAreaVm{LgaName="Ehime Mbano",ReferenceId=295 },
                        new LocalGovernmentAreaVm{LgaName="Ezinihitte",ReferenceId=296 },
                        new LocalGovernmentAreaVm{LgaName="Ideato North",ReferenceId=297 },
                        new LocalGovernmentAreaVm{LgaName="Ideato South",ReferenceId=298 },
                        new LocalGovernmentAreaVm{LgaName="Ihitte/Uboma",ReferenceId=299 },
                        new LocalGovernmentAreaVm{LgaName="Ikeduru",ReferenceId=300 },
                        new LocalGovernmentAreaVm{LgaName="Isiala Mbano",ReferenceId=301 },
                        new LocalGovernmentAreaVm{LgaName="Isu",ReferenceId=302 },
                        new LocalGovernmentAreaVm{LgaName="Mbaitoli",ReferenceId=303 },
                        new LocalGovernmentAreaVm{LgaName="Ngor Okpala",ReferenceId=304 },
                        new LocalGovernmentAreaVm{LgaName="Njaba",ReferenceId=305 },
                        new LocalGovernmentAreaVm{LgaName="Nkwerre",ReferenceId=306 },
                        new LocalGovernmentAreaVm{LgaName="Nwangele",ReferenceId=307 },
                        new LocalGovernmentAreaVm{LgaName="Obowo",ReferenceId=308 },
                        new LocalGovernmentAreaVm{LgaName="Oguta",ReferenceId=309 },
                        new LocalGovernmentAreaVm{LgaName="Ohaji Egbema",ReferenceId=310 },
                        new LocalGovernmentAreaVm{LgaName="Okigwe",ReferenceId=311 },
                        new LocalGovernmentAreaVm{LgaName="Unuimo",ReferenceId=312 },
                        new LocalGovernmentAreaVm{LgaName="Orlu",ReferenceId=313 },
                        new LocalGovernmentAreaVm{LgaName="Orsu",ReferenceId=314 },
                        new LocalGovernmentAreaVm{LgaName="Oru East",ReferenceId=315 },
                        new LocalGovernmentAreaVm{LgaName="Oru West",ReferenceId=316 },
                        new LocalGovernmentAreaVm{LgaName="Owerri Municipal",ReferenceId=317 },
                        new LocalGovernmentAreaVm{LgaName="Owerri North",ReferenceId=318 },
                        new LocalGovernmentAreaVm{LgaName="Owerri West",ReferenceId=319 } }
                },
               
                {
                    "JIGAWA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Auyo",ReferenceId=320 },
                        new LocalGovernmentAreaVm{LgaName="Babura",ReferenceId=321 },
                        new LocalGovernmentAreaVm{LgaName="Biriniwa",ReferenceId=322 },
                        new LocalGovernmentAreaVm{LgaName="Birnin Kudu",ReferenceId=323 },
                        new LocalGovernmentAreaVm{LgaName="Buji",ReferenceId=324 },
                        new LocalGovernmentAreaVm{LgaName="Dutse",ReferenceId=325 },
                        new LocalGovernmentAreaVm{LgaName="Gagarawa",ReferenceId=326 },
                        new LocalGovernmentAreaVm{LgaName="Garki",ReferenceId=327 },
                        new LocalGovernmentAreaVm{LgaName="Gumel",ReferenceId=328 },
                        new LocalGovernmentAreaVm{LgaName="Guri",ReferenceId=329 },
                        new LocalGovernmentAreaVm{LgaName="Gwaram",ReferenceId=330 },
                        new LocalGovernmentAreaVm{LgaName="Gwiwa",ReferenceId=331 },
                        new LocalGovernmentAreaVm{LgaName="Hadejia",ReferenceId=332 },
                        new LocalGovernmentAreaVm{LgaName="Jahun",ReferenceId=333 },
                        new LocalGovernmentAreaVm{LgaName="Kafin Hausa",ReferenceId=334 },
                        new LocalGovernmentAreaVm{LgaName="Kazaure",ReferenceId=335 },
                        new LocalGovernmentAreaVm{LgaName="Kiri Kasama",ReferenceId=336 },
                        new LocalGovernmentAreaVm{LgaName="Kiyawa",ReferenceId=337 },
                        new LocalGovernmentAreaVm{LgaName="Kaugama",ReferenceId=338 },
                        new LocalGovernmentAreaVm{LgaName="Maigatari",ReferenceId=339 },
                        new LocalGovernmentAreaVm{LgaName="Malam Madori",ReferenceId=340 },
                        new LocalGovernmentAreaVm{LgaName="Miga",ReferenceId=341 },
                        new LocalGovernmentAreaVm{LgaName="Ringim",ReferenceId=342 },
                        new LocalGovernmentAreaVm{LgaName="Roni",ReferenceId=343 },
                        new LocalGovernmentAreaVm{LgaName="Sule Tankarkar",ReferenceId=344 },
                        new LocalGovernmentAreaVm{LgaName="Taura",ReferenceId=345 },
                        new LocalGovernmentAreaVm{LgaName="Yankwashi",ReferenceId=346 } }
                },
                {
                    "KADUNA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Birni-Gwari",ReferenceId=347 },
                        new LocalGovernmentAreaVm{LgaName="Chikun",ReferenceId=348 },
                        new LocalGovernmentAreaVm{LgaName="Giwa",ReferenceId=349 },
                        new LocalGovernmentAreaVm{LgaName="Igabi",ReferenceId=350 },
                        new LocalGovernmentAreaVm{LgaName="Ikara",ReferenceId=351 },
                        new LocalGovernmentAreaVm{LgaName="Jaba",ReferenceId=352 },
                        new LocalGovernmentAreaVm{LgaName="Jemaa",ReferenceId=353 },
                        new LocalGovernmentAreaVm{LgaName="Kachia",ReferenceId=354 },
                        new LocalGovernmentAreaVm{LgaName="Kaduna North",ReferenceId=355 },
                        new LocalGovernmentAreaVm{LgaName="Kaduna South",ReferenceId=356 },
                        new LocalGovernmentAreaVm{LgaName="Kagarko",ReferenceId=357 },
                        new LocalGovernmentAreaVm{LgaName="Kajuru",ReferenceId=358 },
                        new LocalGovernmentAreaVm{LgaName="Kaura",ReferenceId=359 },
                        new LocalGovernmentAreaVm{LgaName="Kauru",ReferenceId=360 },
                        new LocalGovernmentAreaVm{LgaName="Kubau",ReferenceId=361 },
                        new LocalGovernmentAreaVm{LgaName="Kudan",ReferenceId=362 },
                        new LocalGovernmentAreaVm{LgaName="Lere",ReferenceId=363 },
                        new LocalGovernmentAreaVm{LgaName="Makarfi",ReferenceId=364 },
                        new LocalGovernmentAreaVm{LgaName="Sabon Gari",ReferenceId=365 },
                        new LocalGovernmentAreaVm{LgaName="Sanga",ReferenceId=366 },
                        new LocalGovernmentAreaVm{LgaName="Soba",ReferenceId=367 },
                        new LocalGovernmentAreaVm{LgaName="Zangon Kataf",ReferenceId=368 },
                        new LocalGovernmentAreaVm{LgaName="Zaria",ReferenceId=369 } }
                },
                {
                    "KANO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Ajingi",ReferenceId=370 },
                        new LocalGovernmentAreaVm{LgaName="Albasu",ReferenceId=371 },
                        new LocalGovernmentAreaVm{LgaName="Bagwai",ReferenceId=372 },
                        new LocalGovernmentAreaVm{LgaName="Bebeji",ReferenceId=373 },
                        new LocalGovernmentAreaVm{LgaName="Bichi",ReferenceId=374 },
                        new LocalGovernmentAreaVm{LgaName="Bunkure",ReferenceId=375 },
                        new LocalGovernmentAreaVm{LgaName="Dala",ReferenceId=376 },
                        new LocalGovernmentAreaVm{LgaName="Dambatta",ReferenceId=377 },
                        new LocalGovernmentAreaVm{LgaName="Dawakin Kudu",ReferenceId=378 },
                        new LocalGovernmentAreaVm{LgaName="Dawakin Tofa",ReferenceId=379 },
                        new LocalGovernmentAreaVm{LgaName="Doguwa",ReferenceId=380 },
                        new LocalGovernmentAreaVm{LgaName="Fagge",ReferenceId=381 },
                        new LocalGovernmentAreaVm{LgaName="Gabasawa",ReferenceId=382 },
                        new LocalGovernmentAreaVm{LgaName="Garko",ReferenceId=383 },
                        new LocalGovernmentAreaVm{LgaName="Garun Mallam",ReferenceId=384 },
                        new LocalGovernmentAreaVm{LgaName="Gaya",ReferenceId=385 },
                        new LocalGovernmentAreaVm{LgaName="Gezawa",ReferenceId=386 },
                        new LocalGovernmentAreaVm{LgaName="Gwale",ReferenceId=387 },
                        new LocalGovernmentAreaVm{LgaName="Gwarzo",ReferenceId=388 },
                        new LocalGovernmentAreaVm{LgaName="Kabo",ReferenceId=389 },
                        new LocalGovernmentAreaVm{LgaName="Kano Municipal",ReferenceId=390 },
                        new LocalGovernmentAreaVm{LgaName="Karaye",ReferenceId=391 },
                        new LocalGovernmentAreaVm{LgaName="Kibiya",ReferenceId=392 },
                        new LocalGovernmentAreaVm{LgaName="Kiru",ReferenceId=393 },
                        new LocalGovernmentAreaVm{LgaName="Kumbotso",ReferenceId=394 },
                        new LocalGovernmentAreaVm{LgaName="Kunchi",ReferenceId=395 },
                        new LocalGovernmentAreaVm{LgaName="Kura",ReferenceId=396 },
                        new LocalGovernmentAreaVm{LgaName="Madobi",ReferenceId=397 },
                        new LocalGovernmentAreaVm{LgaName="Makoda",ReferenceId=398 },
                        new LocalGovernmentAreaVm{LgaName="Minjibir",ReferenceId=399 },
                        new LocalGovernmentAreaVm{LgaName="Nasarawa",ReferenceId=400 },
                        new LocalGovernmentAreaVm{LgaName="Rano",ReferenceId=401 },
                        new LocalGovernmentAreaVm{LgaName="Rimin Gado",ReferenceId=402 },
                        new LocalGovernmentAreaVm{LgaName="Rogo",ReferenceId=403 },
                        new LocalGovernmentAreaVm{LgaName="Shanono",ReferenceId=404 },
                        new LocalGovernmentAreaVm{LgaName="Sumaila",ReferenceId=405 },
                        new LocalGovernmentAreaVm{LgaName="Takai",ReferenceId=406 },
                        new LocalGovernmentAreaVm{LgaName="Tarauni",ReferenceId=407 },
                        new LocalGovernmentAreaVm{LgaName="Tofa",ReferenceId=408 },
                        new LocalGovernmentAreaVm{LgaName="Tsanyawa",ReferenceId=409 },
                        new LocalGovernmentAreaVm{LgaName="Tudun Wada",ReferenceId=410 },
                        new LocalGovernmentAreaVm{LgaName="Ungogo",ReferenceId=411 },
                        new LocalGovernmentAreaVm{LgaName="Warawa",ReferenceId=412 },
                        new LocalGovernmentAreaVm{LgaName="Wudil",ReferenceId=413 } }
                },
                {
                    "KATSINA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Bakori",ReferenceId=414 },
                        new LocalGovernmentAreaVm{LgaName="Batagarawa",ReferenceId=415 },
                        new LocalGovernmentAreaVm{LgaName="Batsari",ReferenceId=416 },
                        new LocalGovernmentAreaVm{LgaName="Baure",ReferenceId=417 },
                        new LocalGovernmentAreaVm{LgaName="Bindawa",ReferenceId=418 },
                        new LocalGovernmentAreaVm{LgaName="Charanchi",ReferenceId=419 },
                        new LocalGovernmentAreaVm{LgaName="Dandume",ReferenceId=420 },
                        new LocalGovernmentAreaVm{LgaName="Danja",ReferenceId=421 },
                        new LocalGovernmentAreaVm{LgaName="Dan Musa",ReferenceId=422 },
                        new LocalGovernmentAreaVm{LgaName="Daura",ReferenceId=423 },
                        new LocalGovernmentAreaVm{LgaName="Dutsi",ReferenceId=424 },
                        new LocalGovernmentAreaVm{LgaName="Dutsin Ma",ReferenceId=425 },
                        new LocalGovernmentAreaVm{LgaName="Faskari",ReferenceId=426 },
                        new LocalGovernmentAreaVm{LgaName="Funtua",ReferenceId=427 },
                        new LocalGovernmentAreaVm{LgaName="Ingawa",ReferenceId=428 },
                        new LocalGovernmentAreaVm{LgaName="Jibia",ReferenceId=429 },
                        new LocalGovernmentAreaVm{LgaName="Kafur",ReferenceId=430 },
                        new LocalGovernmentAreaVm{LgaName="Kaita",ReferenceId=431 },
                        new LocalGovernmentAreaVm{LgaName="Kankara",ReferenceId=432 },
                        new LocalGovernmentAreaVm{LgaName="Kankia",ReferenceId=433 },
                        new LocalGovernmentAreaVm{LgaName="Katsina",ReferenceId=434 },
                        new LocalGovernmentAreaVm{LgaName="Kurfi",ReferenceId=435 },
                        new LocalGovernmentAreaVm{LgaName="Kusada",ReferenceId=436 },
                        new LocalGovernmentAreaVm{LgaName="Mai'Adua",ReferenceId=437 },
                        new LocalGovernmentAreaVm{LgaName="Malumfashi",ReferenceId=438 },
                        new LocalGovernmentAreaVm{LgaName="Mani",ReferenceId=439 },
                        new LocalGovernmentAreaVm{LgaName="Mashi",ReferenceId=440 },
                        new LocalGovernmentAreaVm{LgaName="Matazu",ReferenceId=441 },
                        new LocalGovernmentAreaVm{LgaName="Musawa",ReferenceId=442 },
                        new LocalGovernmentAreaVm{LgaName="Rimi",ReferenceId=443 },
                        new LocalGovernmentAreaVm{LgaName="Sabuwa",ReferenceId=444 },
                        new LocalGovernmentAreaVm{LgaName="Safana",ReferenceId=445 },
                        new LocalGovernmentAreaVm{LgaName="Sandamu",ReferenceId=446 },
                        new LocalGovernmentAreaVm{LgaName="Zango",ReferenceId=447 } }
                },
                {
                    "KEBBI",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aleiro",ReferenceId=448 },
                        new LocalGovernmentAreaVm{LgaName="Arewa Dandi",ReferenceId=449 },
                        new LocalGovernmentAreaVm{LgaName="Argungu",ReferenceId=450 },
                        new LocalGovernmentAreaVm{LgaName="Augie",ReferenceId=451 },
                        new LocalGovernmentAreaVm{LgaName="Bagudo",ReferenceId=452 },
                        new LocalGovernmentAreaVm{LgaName="Birnin Kebbi",ReferenceId=453 },
                        new LocalGovernmentAreaVm{LgaName="Bunza",ReferenceId=454 },
                        new LocalGovernmentAreaVm{LgaName="Dandi",ReferenceId=455 },
                        new LocalGovernmentAreaVm{LgaName="Fakai",ReferenceId=456 },
                        new LocalGovernmentAreaVm{LgaName="Gwandu",ReferenceId=457 },
                        new LocalGovernmentAreaVm{LgaName="Jega",ReferenceId=458 },
                        new LocalGovernmentAreaVm{LgaName="Kalgo",ReferenceId=459 },
                        new LocalGovernmentAreaVm{LgaName="Koko Besse",ReferenceId=460 },
                        new LocalGovernmentAreaVm{LgaName="Maiyama",ReferenceId=461 },
                        new LocalGovernmentAreaVm{LgaName="Ngaski",ReferenceId=462 },
                        new LocalGovernmentAreaVm{LgaName="Sakaba",ReferenceId=463 },
                        new LocalGovernmentAreaVm{LgaName="Shanga",ReferenceId=464 },
                        new LocalGovernmentAreaVm{LgaName="Suru",ReferenceId=465 },
                        new LocalGovernmentAreaVm{LgaName="Wasagu Danko",ReferenceId=466 },
                        new LocalGovernmentAreaVm{LgaName="Yauri",ReferenceId=467 },
                        new LocalGovernmentAreaVm{LgaName="Zuru",ReferenceId=468 } }
                },
                {
                    "KOGI",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Adavi",ReferenceId=469 },
                        new LocalGovernmentAreaVm{LgaName="Ajaokuta",ReferenceId=470 },
                        new LocalGovernmentAreaVm{LgaName="Ankpa",ReferenceId=471 },
                        new LocalGovernmentAreaVm{LgaName="Bassa",ReferenceId=472 },
                        new LocalGovernmentAreaVm{LgaName="Dekina",ReferenceId=473 },
                        new LocalGovernmentAreaVm{LgaName="Ibaji",ReferenceId=474 },
                        new LocalGovernmentAreaVm{LgaName="Idah",ReferenceId=475 },
                        new LocalGovernmentAreaVm{LgaName="Igalamela Odolu",ReferenceId=476 },
                        new LocalGovernmentAreaVm{LgaName="Ijumu",ReferenceId=477 },
                        new LocalGovernmentAreaVm{LgaName="Kabba/Bunu",ReferenceId=478 },
                        new LocalGovernmentAreaVm{LgaName="Kogi",ReferenceId=479 },
                        new LocalGovernmentAreaVm{LgaName="Lokoja",ReferenceId=480 },
                        new LocalGovernmentAreaVm{LgaName="Mopa Muro",ReferenceId=481 },
                        new LocalGovernmentAreaVm{LgaName="Ofu",ReferenceId=482 },
                        new LocalGovernmentAreaVm{LgaName="Ogori Magongo",ReferenceId=483 },
                        new LocalGovernmentAreaVm{LgaName="Okehi",ReferenceId=484 },
                        new LocalGovernmentAreaVm{LgaName="Okene",ReferenceId=485 },
                        new LocalGovernmentAreaVm{LgaName="Olamaboro",ReferenceId=486 },
                        new LocalGovernmentAreaVm{LgaName="Omala",ReferenceId=487 },
                        new LocalGovernmentAreaVm{LgaName="Yagba East",ReferenceId=488 },
                        new LocalGovernmentAreaVm{LgaName="Yagba West",ReferenceId=489 } }
                },
                {
                    "KWARA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Asa",ReferenceId=490 },
                        new LocalGovernmentAreaVm{LgaName="Baruten",ReferenceId=491 },
                        new LocalGovernmentAreaVm{LgaName="Edu",ReferenceId=492 },
                        new LocalGovernmentAreaVm{LgaName="Ekiti",ReferenceId=493 },
                        new LocalGovernmentAreaVm{LgaName="Ifelodun",ReferenceId=494 },
                        new LocalGovernmentAreaVm{LgaName="Ilorin East",ReferenceId=495 },
                        new LocalGovernmentAreaVm{LgaName="Ilorin South",ReferenceId=496 },
                        new LocalGovernmentAreaVm{LgaName="Ilorin West",ReferenceId=497 },
                        new LocalGovernmentAreaVm{LgaName="Irepodun",ReferenceId=498 },
                        new LocalGovernmentAreaVm{LgaName="Isin",ReferenceId=499 },
                        new LocalGovernmentAreaVm{LgaName="Kaiama",ReferenceId=500 },
                        new LocalGovernmentAreaVm{LgaName="Moro",ReferenceId=501 },
                        new LocalGovernmentAreaVm{LgaName="Offa",ReferenceId=502 },
                        new LocalGovernmentAreaVm{LgaName="Oke Ero",ReferenceId=503 },
                        new LocalGovernmentAreaVm{LgaName="Oyun",ReferenceId=504 },
                        new LocalGovernmentAreaVm{LgaName="Pategi",ReferenceId=505 } }
                },
                {
                    "LAGOS",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Agege",ReferenceId=506 },
                        new LocalGovernmentAreaVm{LgaName="Ajeromi-Ifelodun",ReferenceId=507 },
                        new LocalGovernmentAreaVm{LgaName="Alimosho",ReferenceId=508 },
                        new LocalGovernmentAreaVm{LgaName="Amuwo-Odofin",ReferenceId=509 },
                        new LocalGovernmentAreaVm{LgaName="Apapa",ReferenceId=510 },
                        new LocalGovernmentAreaVm{LgaName="Badagry",ReferenceId=511 },
                        new LocalGovernmentAreaVm{LgaName="Epe",ReferenceId=512 },
                        new LocalGovernmentAreaVm{LgaName="Eti Osa",ReferenceId=513 },
                        new LocalGovernmentAreaVm{LgaName="Ibeju-Lekki",ReferenceId=514 },
                        new LocalGovernmentAreaVm{LgaName="Ifako-Ijaiye",ReferenceId=515 },
                        new LocalGovernmentAreaVm{LgaName="Ikeja",ReferenceId=516 },
                        new LocalGovernmentAreaVm{LgaName="Ikorodu",ReferenceId=517 },
                        new LocalGovernmentAreaVm{LgaName="Kosofe",ReferenceId=518 },
                        new LocalGovernmentAreaVm{LgaName="Lagos Island",ReferenceId=519 },
                        new LocalGovernmentAreaVm{LgaName="Lagos Mainland",ReferenceId=520 },
                        new LocalGovernmentAreaVm{LgaName="Mushin",ReferenceId=521 },
                        new LocalGovernmentAreaVm{LgaName="Ojo",ReferenceId=522 },
                        new LocalGovernmentAreaVm{LgaName="Oshodi-Isolo",ReferenceId=523 },
                        new LocalGovernmentAreaVm{LgaName="Shomolu",ReferenceId=524 },
                        new LocalGovernmentAreaVm{LgaName="Surulere",ReferenceId=525 } }
                },
                {
                    "NASARAWA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Akwanga",ReferenceId=526 },
                        new LocalGovernmentAreaVm{LgaName="Awe",ReferenceId=527 },
                        new LocalGovernmentAreaVm{LgaName="Doma",ReferenceId=528 },
                        new LocalGovernmentAreaVm{LgaName="Karu",ReferenceId=529 },
                        new LocalGovernmentAreaVm{LgaName="Keana",ReferenceId=530 },
                        new LocalGovernmentAreaVm{LgaName="Keffi",ReferenceId=531 },
                        new LocalGovernmentAreaVm{LgaName="Kokona",ReferenceId=532 },
                        new LocalGovernmentAreaVm{LgaName="Lafia",ReferenceId=533 },
                        new LocalGovernmentAreaVm{LgaName="Nasarawa",ReferenceId=534 },
                        new LocalGovernmentAreaVm{LgaName="Nasarawa Egon",ReferenceId=535 },
                        new LocalGovernmentAreaVm{LgaName="Obi",ReferenceId=536 },
                        new LocalGovernmentAreaVm{LgaName="Toto",ReferenceId=537 },
                        new LocalGovernmentAreaVm{LgaName="Wamba",ReferenceId=538 } }
                },
                {
                    "NIGER",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Agaie",ReferenceId=539 },
                        new LocalGovernmentAreaVm{LgaName="Agwara",ReferenceId=540 },
                        new LocalGovernmentAreaVm{LgaName="Bida",ReferenceId=541 },
                        new LocalGovernmentAreaVm{LgaName="Borgu",ReferenceId=542 },
                        new LocalGovernmentAreaVm{LgaName="Bosso",ReferenceId=543 },
                        new LocalGovernmentAreaVm{LgaName="Chanchaga",ReferenceId=544 },
                        new LocalGovernmentAreaVm{LgaName="Edati",ReferenceId=545 },
                        new LocalGovernmentAreaVm{LgaName="Gbako",ReferenceId=546 },
                        new LocalGovernmentAreaVm{LgaName="Gurara",ReferenceId=547 },
                        new LocalGovernmentAreaVm{LgaName="Katcha",ReferenceId=548 },
                        new LocalGovernmentAreaVm{LgaName="Kontagora",ReferenceId=549 },
                        new LocalGovernmentAreaVm{LgaName="Lapai",ReferenceId=550 },
                        new LocalGovernmentAreaVm{LgaName="Lavun",ReferenceId=551 },
                        new LocalGovernmentAreaVm{LgaName="Magama",ReferenceId=552 },
                        new LocalGovernmentAreaVm{LgaName="Mariga",ReferenceId=553 },
                        new LocalGovernmentAreaVm{LgaName="Mashegu",ReferenceId=554 },
                        new LocalGovernmentAreaVm{LgaName="Mokwa",ReferenceId=555 },
                        new LocalGovernmentAreaVm{LgaName="Moya",ReferenceId=556 },
                        new LocalGovernmentAreaVm{LgaName="Paikoro",ReferenceId=557 },
                        new LocalGovernmentAreaVm{LgaName="Rafi",ReferenceId=558 },
                        new LocalGovernmentAreaVm{LgaName="Rijau",ReferenceId=559 },
                        new LocalGovernmentAreaVm{LgaName="Shiroro",ReferenceId=560 },
                        new LocalGovernmentAreaVm{LgaName="Suleja",ReferenceId=561 },
                        new LocalGovernmentAreaVm{LgaName="Tafa",ReferenceId=562 },
                        new LocalGovernmentAreaVm{LgaName="Wushishi",ReferenceId=563 } }
                },
                {
                    "OGUN",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Abeokuta North",ReferenceId=564 },
                        new LocalGovernmentAreaVm{LgaName="Abeokuta South",ReferenceId=565 },
                        new LocalGovernmentAreaVm{LgaName="Ado-Odo Ota",ReferenceId=566 },
                        new LocalGovernmentAreaVm{LgaName="Egbado North",ReferenceId=567 },
                        new LocalGovernmentAreaVm{LgaName="Egbado South",ReferenceId=568 },
                        new LocalGovernmentAreaVm{LgaName="Ewekoro",ReferenceId=569 },
                        new LocalGovernmentAreaVm{LgaName="Ifo",ReferenceId=570 },
                        new LocalGovernmentAreaVm{LgaName="Ijebu East",ReferenceId=571 },
                        new LocalGovernmentAreaVm{LgaName="Ijebu North",ReferenceId=572 },
                        new LocalGovernmentAreaVm{LgaName="Ijebu North East",ReferenceId=573 },
                        new LocalGovernmentAreaVm{LgaName="Ijebu Ode",ReferenceId=574 },
                        new LocalGovernmentAreaVm{LgaName="Ikenne",ReferenceId=575 },
                        new LocalGovernmentAreaVm{LgaName="Imeko Afon",ReferenceId=576 },
                        new LocalGovernmentAreaVm{LgaName="Ipokia",ReferenceId=577 },
                        new LocalGovernmentAreaVm{LgaName="Obafemi Owode",ReferenceId=578 },
                        new LocalGovernmentAreaVm{LgaName="Odeda",ReferenceId=579 },
                        new LocalGovernmentAreaVm{LgaName="Odogbolu",ReferenceId=580 },
                        new LocalGovernmentAreaVm{LgaName="Ogun Waterside",ReferenceId=581 },
                        new LocalGovernmentAreaVm{LgaName="Remo North",ReferenceId=582 },
                        new LocalGovernmentAreaVm{LgaName="Shagamu",ReferenceId=583 } }
                },
                {
                    "ONDO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Akoko North-East",ReferenceId=584 },
                        new LocalGovernmentAreaVm{LgaName="Akoko North-West",ReferenceId=585 },
                        new LocalGovernmentAreaVm{LgaName="Akoko South-West",ReferenceId=586 },
                        new LocalGovernmentAreaVm{LgaName="Akoko South-East",ReferenceId=587 },
                        new LocalGovernmentAreaVm{LgaName="Akure North",ReferenceId=588 },
                        new LocalGovernmentAreaVm{LgaName="Akure South",ReferenceId=589 },
                        new LocalGovernmentAreaVm{LgaName="Ese Odo",ReferenceId=590 },
                        new LocalGovernmentAreaVm{LgaName="Idanre",ReferenceId=591 },
                        new LocalGovernmentAreaVm{LgaName="Ifedore",ReferenceId=592 },
                        new LocalGovernmentAreaVm{LgaName="Ilaje",ReferenceId=593 },
                        new LocalGovernmentAreaVm{LgaName="Ile Oluji Okeigbo",ReferenceId=594 },
                        new LocalGovernmentAreaVm{LgaName="Irele",ReferenceId=595 },
                        new LocalGovernmentAreaVm{LgaName="Odigbo",ReferenceId=596 },
                        new LocalGovernmentAreaVm{LgaName="Okitipupa",ReferenceId=597 },
                        new LocalGovernmentAreaVm{LgaName="Ondo East",ReferenceId=598 },
                        new LocalGovernmentAreaVm{LgaName="Ondo West",ReferenceId=599 },
                        new LocalGovernmentAreaVm{LgaName="Ose",ReferenceId=600 },
                        new LocalGovernmentAreaVm{LgaName="Owo",ReferenceId=601 } }
                },
                {
                    "OSUN",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Aiyedaade",ReferenceId=602 },
                        new LocalGovernmentAreaVm{LgaName="Aiyedire",ReferenceId=603 },
                        new LocalGovernmentAreaVm{LgaName="Atakumosa East",ReferenceId=604 },
                        new LocalGovernmentAreaVm{LgaName="Atakumosa West",ReferenceId=605 },
                        new LocalGovernmentAreaVm{LgaName="Boluwaduro",ReferenceId=606 },
                        new LocalGovernmentAreaVm{LgaName="Boripe",ReferenceId=607 },
                        new LocalGovernmentAreaVm{LgaName="Ede North",ReferenceId=608 },
                        new LocalGovernmentAreaVm{LgaName="Ede South",ReferenceId=609 },
                        new LocalGovernmentAreaVm{LgaName="Egbedore",ReferenceId=610 },
                        new LocalGovernmentAreaVm{LgaName="Ejigbo",ReferenceId=611 },
                        new LocalGovernmentAreaVm{LgaName="Ife Central",ReferenceId=612 },
                        new LocalGovernmentAreaVm{LgaName="Ife East",ReferenceId=613 },
                        new LocalGovernmentAreaVm{LgaName="Ife North",ReferenceId=614 },
                        new LocalGovernmentAreaVm{LgaName="Ife South",ReferenceId=615 },
                        new LocalGovernmentAreaVm{LgaName="Ifedayo",ReferenceId=616 },
                        new LocalGovernmentAreaVm{LgaName="Ifelodun",ReferenceId=617 },
                        new LocalGovernmentAreaVm{LgaName="Ila",ReferenceId=618 },
                        new LocalGovernmentAreaVm{LgaName="Ilesha East",ReferenceId=619 },
                        new LocalGovernmentAreaVm{LgaName="Ilesha West", ReferenceId=620 },
                        new LocalGovernmentAreaVm{LgaName="Irepodun",ReferenceId=621 },
                        new LocalGovernmentAreaVm{LgaName="Irewole",ReferenceId=622 },
                        new LocalGovernmentAreaVm{LgaName="Isokan",ReferenceId=623 },
                        new LocalGovernmentAreaVm{LgaName="Iwo",ReferenceId=624 },
                        new LocalGovernmentAreaVm{LgaName="Obokun",ReferenceId=625 },
                        new LocalGovernmentAreaVm{LgaName="Odo-Otin",ReferenceId=626 },
                        new LocalGovernmentAreaVm{LgaName="Ola-Oluwa",ReferenceId=627 },
                        new LocalGovernmentAreaVm{LgaName="Olarunda",ReferenceId=628 },
                        new LocalGovernmentAreaVm{LgaName="Oriade",ReferenceId=629 },
                        new LocalGovernmentAreaVm{LgaName="Orolu",ReferenceId=630 },
                        new LocalGovernmentAreaVm{LgaName="Osogbo",ReferenceId=631 } }
                },
                {
                    "OYO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Afijio",ReferenceId=632 },
                        new LocalGovernmentAreaVm{LgaName="Akinyele",ReferenceId=633 },
                        new LocalGovernmentAreaVm{LgaName="Atiba",ReferenceId=634 },
                        new LocalGovernmentAreaVm{LgaName="Atisbo",ReferenceId=635 },
                        new LocalGovernmentAreaVm{LgaName="Egbeda",ReferenceId=636 },
                        new LocalGovernmentAreaVm{LgaName="Ibadan North",ReferenceId=637 },
                        new LocalGovernmentAreaVm{LgaName="Ibadan North-East",ReferenceId=638 },
                        new LocalGovernmentAreaVm{LgaName="Ibadan North-West",ReferenceId=639 },
                        new LocalGovernmentAreaVm{LgaName="Ibadan South-East",ReferenceId=640 },
                        new LocalGovernmentAreaVm{LgaName="Ibadan South-West",ReferenceId=641 },
                        new LocalGovernmentAreaVm{LgaName="Ibarapa Central",ReferenceId=642 },
                        new LocalGovernmentAreaVm{LgaName="Ibarapa East",ReferenceId=643 },
                        new LocalGovernmentAreaVm{LgaName="Ibarapa North",ReferenceId=644 },
                        new LocalGovernmentAreaVm{LgaName="Ido",ReferenceId=645 },
                        new LocalGovernmentAreaVm{LgaName="Irepo",ReferenceId=646 },
                        new LocalGovernmentAreaVm{LgaName="Iseyin",ReferenceId=647 },
                        new LocalGovernmentAreaVm{LgaName="Itesiwaju",ReferenceId=648 },
                        new LocalGovernmentAreaVm{LgaName="Iwajowa",ReferenceId=649 },
                        new LocalGovernmentAreaVm{LgaName="Kajola",ReferenceId=650 },
                        new LocalGovernmentAreaVm{LgaName="Lagelu",ReferenceId=651 },
                        new LocalGovernmentAreaVm{LgaName="Ogbomosho North",ReferenceId=652 },
                        new LocalGovernmentAreaVm{LgaName="Ogbomosho South",ReferenceId=653 },
                        new LocalGovernmentAreaVm{LgaName="Ogo Oluwa",ReferenceId=654 },
                        new LocalGovernmentAreaVm{LgaName="Olorunsogo",ReferenceId=655 },
                        new LocalGovernmentAreaVm{LgaName="Oluyole",ReferenceId=656 },
                        new LocalGovernmentAreaVm{LgaName="Ona Ara",ReferenceId=657 },
                        new LocalGovernmentAreaVm{LgaName="Orelope",ReferenceId=658 },
                        new LocalGovernmentAreaVm{LgaName="Ori Ire",ReferenceId=659 },
                        new LocalGovernmentAreaVm{LgaName="Oyo",ReferenceId=660 },
                        new LocalGovernmentAreaVm{LgaName="Oyo East",ReferenceId=661 },
                        new LocalGovernmentAreaVm{LgaName="Saki East",ReferenceId=662 },
                        new LocalGovernmentAreaVm{LgaName="Saki West",ReferenceId=663 },
                        new LocalGovernmentAreaVm{LgaName="Surulere",ReferenceId=664 } }
                },
                {
                    "PLATEAU",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Barkin Ladi",ReferenceId=665 },
                        new LocalGovernmentAreaVm{LgaName="Bassa",ReferenceId=666 },
                        new LocalGovernmentAreaVm{LgaName="Bokkos",ReferenceId=667 },
                        new LocalGovernmentAreaVm{LgaName="Jos East",ReferenceId=668 },
                        new LocalGovernmentAreaVm{LgaName="Jos North",ReferenceId=669 },
                        new LocalGovernmentAreaVm{LgaName="Jos South",ReferenceId=670 },
                        new LocalGovernmentAreaVm{LgaName="Kanam",ReferenceId=671 },
                        new LocalGovernmentAreaVm{LgaName="Kanke",ReferenceId=672 },
                        new LocalGovernmentAreaVm{LgaName="Langtang South",ReferenceId=673 },
                        new LocalGovernmentAreaVm{LgaName="Langtang North",ReferenceId=674 },
                        new LocalGovernmentAreaVm{LgaName="Mangu",ReferenceId=675 },
                        new LocalGovernmentAreaVm{LgaName="Mikang",ReferenceId=676 },
                        new LocalGovernmentAreaVm{LgaName="Pankshin",ReferenceId=677 },
                        new LocalGovernmentAreaVm{LgaName="Qua'an Pan",ReferenceId=678 },
                        new LocalGovernmentAreaVm{LgaName="Riyom",ReferenceId=679 },
                        new LocalGovernmentAreaVm{LgaName="Shendam",ReferenceId=680 },
                        new LocalGovernmentAreaVm{LgaName="Wase",ReferenceId=681 } }
                },
                {
                    "RIVERS",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Abua/Odual",ReferenceId=682 },
                        new LocalGovernmentAreaVm{LgaName="Ahoada East",ReferenceId=683 },
                        new LocalGovernmentAreaVm{LgaName="Ahoada West",ReferenceId=684 },
                        new LocalGovernmentAreaVm{LgaName="Akuku-Toru",ReferenceId=685 },
                        new LocalGovernmentAreaVm{LgaName="Andoni",ReferenceId=686 },
                        new LocalGovernmentAreaVm{LgaName="Asari-Toru",ReferenceId=687 },
                        new LocalGovernmentAreaVm{LgaName="Bonny",ReferenceId=688 },
                        new LocalGovernmentAreaVm{LgaName="Degema",ReferenceId=689 },
                        new LocalGovernmentAreaVm{LgaName="Eleme",ReferenceId=690 },
                        new LocalGovernmentAreaVm{LgaName="Emuoha",ReferenceId=691 },
                        new LocalGovernmentAreaVm{LgaName="Etche",ReferenceId=692 },
                        new LocalGovernmentAreaVm{LgaName="Gokana",ReferenceId=693 },
                        new LocalGovernmentAreaVm{LgaName="Ikwerre",ReferenceId=694 },
                        new LocalGovernmentAreaVm{LgaName="Khana",ReferenceId=695 },
                        new LocalGovernmentAreaVm{LgaName="Obio Akpor",ReferenceId=696 },
                        new LocalGovernmentAreaVm{LgaName="Ogba Egbema Ndoni",ReferenceId=697 },
                        new LocalGovernmentAreaVm{LgaName="Ogu Bolo",ReferenceId=698 },
                        new LocalGovernmentAreaVm{LgaName="Okrika",ReferenceId=699 },
                        new LocalGovernmentAreaVm{LgaName="Omuma",ReferenceId=700 },
                        new LocalGovernmentAreaVm{LgaName="Opobo Nkoro",ReferenceId=701 },
                        new LocalGovernmentAreaVm{LgaName="Oyigbo",ReferenceId=702 },
                        new LocalGovernmentAreaVm{LgaName="Port Harcourt",ReferenceId=703 },
                        new LocalGovernmentAreaVm{LgaName="Tai",ReferenceId=704 } }
                },
                {
                    "SOKOTO",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Binji",ReferenceId=705 },
                        new LocalGovernmentAreaVm{LgaName="Bodinga",ReferenceId=706 },
                        new LocalGovernmentAreaVm{LgaName="Dange Shuni",ReferenceId=707 },
                        new LocalGovernmentAreaVm{LgaName="Gada",ReferenceId=708 },
                        new LocalGovernmentAreaVm{LgaName="Goronyo",ReferenceId=709 },
                        new LocalGovernmentAreaVm{LgaName="Gudu",ReferenceId=710 },
                        new LocalGovernmentAreaVm{LgaName="Gwadabawa",ReferenceId=711 },
                        new LocalGovernmentAreaVm{LgaName="Illela",ReferenceId=712 },
                        new LocalGovernmentAreaVm{LgaName="Isa",ReferenceId=713 },
                        new LocalGovernmentAreaVm{LgaName="Kebbe",ReferenceId=714 },
                        new LocalGovernmentAreaVm{LgaName="Kware",ReferenceId=715 },
                        new LocalGovernmentAreaVm{LgaName="Rabah",ReferenceId=716 },
                        new LocalGovernmentAreaVm{LgaName="Sabon Birni",ReferenceId=717 },
                        new LocalGovernmentAreaVm{LgaName="Shagari",ReferenceId=718 },
                        new LocalGovernmentAreaVm{LgaName="Silame",ReferenceId=719 },
                        new LocalGovernmentAreaVm{LgaName="Sokoto North",ReferenceId=720 },
                        new LocalGovernmentAreaVm{LgaName="Sokoto South",ReferenceId=721 },
                        new LocalGovernmentAreaVm{LgaName="Tambuwal",ReferenceId=722 },
                        new LocalGovernmentAreaVm{LgaName="Tangaza",ReferenceId=723 },
                        new LocalGovernmentAreaVm{LgaName="Tureta",ReferenceId=724 },
                        new LocalGovernmentAreaVm{LgaName="Wamako",ReferenceId=725 },
                        new LocalGovernmentAreaVm{LgaName="Wurno",ReferenceId=726 },
                        new LocalGovernmentAreaVm{LgaName="Yabo",ReferenceId=727 } }
                },
                {
                    "TARABA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Ardo-kola",ReferenceId=728 },
                        new LocalGovernmentAreaVm{LgaName="Bali",ReferenceId=729 },
                        new LocalGovernmentAreaVm{LgaName="Donga",ReferenceId=730 },
                        new LocalGovernmentAreaVm{LgaName="Gashaka",ReferenceId=731 },
                        new LocalGovernmentAreaVm{LgaName="Gassol",ReferenceId=732 },
                        new LocalGovernmentAreaVm{LgaName="Ibi",ReferenceId=733 },
                        new LocalGovernmentAreaVm{LgaName="Jalingo",ReferenceId=734 },
                        new LocalGovernmentAreaVm{LgaName="Karim Lamido",ReferenceId=735 },
                        new LocalGovernmentAreaVm{LgaName="Kumi",ReferenceId=736 },
                        new LocalGovernmentAreaVm{LgaName="Lau",ReferenceId=737 },
                        new LocalGovernmentAreaVm{LgaName="Sardauna",ReferenceId=738 },
                        new LocalGovernmentAreaVm{LgaName="Takum",ReferenceId=739 },
                        new LocalGovernmentAreaVm{LgaName="Ussa",ReferenceId=740 },
                        new LocalGovernmentAreaVm{LgaName="Wukari",ReferenceId=741 },
                        new LocalGovernmentAreaVm{LgaName="Yorro",ReferenceId=742 },
                        new LocalGovernmentAreaVm{LgaName="Zing",ReferenceId=743 } }
                },
                {
                    "YOBE",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Bade",ReferenceId=744 },
                        new LocalGovernmentAreaVm{LgaName="Bursari",ReferenceId=745 },
                        new LocalGovernmentAreaVm{LgaName="Damaturu",ReferenceId=746 },
                        new LocalGovernmentAreaVm{LgaName="Fika",ReferenceId=747 },
                        new LocalGovernmentAreaVm{LgaName="Fune",ReferenceId=748 },
                        new LocalGovernmentAreaVm{LgaName="Geidam",ReferenceId=749 },
                        new LocalGovernmentAreaVm{LgaName="Gujba",ReferenceId=750 },
                        new LocalGovernmentAreaVm{LgaName="Gulani",ReferenceId=751 },
                        new LocalGovernmentAreaVm{LgaName="Jakusko",ReferenceId=752 },
                        new LocalGovernmentAreaVm{LgaName="Karasuwa",ReferenceId=753 },
                        new LocalGovernmentAreaVm{LgaName="Machina",ReferenceId=754 },
                        new LocalGovernmentAreaVm{LgaName="Nangere",ReferenceId=755 },
                        new LocalGovernmentAreaVm{LgaName="Nguru",ReferenceId=756 },
                        new LocalGovernmentAreaVm{LgaName="Potiskum",ReferenceId=757 },
                        new LocalGovernmentAreaVm{LgaName="Tarmuwa",ReferenceId=758 },
                        new LocalGovernmentAreaVm{LgaName="Yunusari",ReferenceId=759 },
                        new LocalGovernmentAreaVm{LgaName="Yusufari",ReferenceId=760 } }
                },
                {
                    "ZAMFARA",
                    new List<LocalGovernmentAreaVm>(){new LocalGovernmentAreaVm{LgaName="Anka",ReferenceId=761 },
                        new LocalGovernmentAreaVm{LgaName="Bakura",ReferenceId=762 },
                        new LocalGovernmentAreaVm{LgaName="Birnin Magaji Kiyaw",ReferenceId=763 },
                        new LocalGovernmentAreaVm{LgaName="Bukkuyum",ReferenceId=764 },
                        new LocalGovernmentAreaVm{LgaName="Bungudu",ReferenceId=765 },
                        new LocalGovernmentAreaVm{LgaName="Gummi",ReferenceId=766 },
                        new LocalGovernmentAreaVm{LgaName="Gusau",ReferenceId=767 },
                        new LocalGovernmentAreaVm{LgaName="Kaura Namoda",ReferenceId=768 },
                        new LocalGovernmentAreaVm{LgaName="Maradun",ReferenceId=769 },
                        new LocalGovernmentAreaVm{LgaName="Maru",ReferenceId=770 },
                        new LocalGovernmentAreaVm{LgaName="Shinkafi",ReferenceId=771 },
                        new LocalGovernmentAreaVm{LgaName="Talata Mafara",ReferenceId=772 },
                        new LocalGovernmentAreaVm{LgaName="Tsafe",ReferenceId=773 },
                        new LocalGovernmentAreaVm{LgaName="Zurmi",ReferenceId=774} }
                }
            };

            return lgaList;
        }

    }
}
